### PR TITLE
Updated lite_wave.py for solving issue #9

### PR DESCRIPTION
**Pull request by sohamsangole**
Added a new method to calculate the duration of the (wav file) audio (in seconds).

### CODE REVIEW

**Comment by sohamsangole** [comment]
Do let me know if I did it correctly or not... This was my first contribution. I would learn alot from this. 
Also.
Thanks for assigning me this issue.

**Review by mthorntonhanks — COMMENTED** [review]
@sohamsangole thank you for your first contribution to my first public repo :) It looks good but I just have a couple of comments. First, the calculation of duration should be based on the size of the data chunk not the size of whole file. So you can use f.get_chunk_size('data') to get the size of the data chunk. Second, what is the reason you have defined the method as static? Do you think there is any advantage to this over a regular instance method? Thanks!

**Comment by sohamsangole** [comment]
@mthorntonhanks Well, I made it static because I did not use the self-parameter and I don't quite understand this data chunk. Can u help me with it?

**Comment by mthorntonhanks** [comment]
@sohamsangole  No problem. The data chunk is the part of the file containing the actual sound data, the other parts of the file contain parameters etc.

**Comment by sohamsangole** [comment]
so how would using the data chunk will benefit rather than using actual size of wave file?

**Comment by mthorntonhanks** [comment]
The wave file contains not only sound data (the data 'chunk'), but also metadata such as the sample rate and bit resolution and so on. So to calculate the duration of the sound accurately, you should use size of the data chunk.

**Comment by sohamsangole** [comment]
Thanks, I learned something new. I am working on the chunk part

**Pull request closed without merging**
